### ISSUE TITLE
ComplexCoverage get_parameter_values raises if using time segment of (None,None)

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#185]
```
======================================================================
ERROR: test_attributes ( coverage_model.test.test_complex_coverage:TestNewComplexCoverageInt.test_attributes )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luke/Documents/Dev/code/coi2/extern/coverage-model/coverage_model/test/test_complex_coverage.py", line 901, in test_attributes
    data = ccov.get_parameter_values(time_segment=(None,None), fill_empty_params=True, as_record_array=False).get_data()
  File "/Users/luke/Documents/Dev/code/coi2/extern/coverage-model/coverage_model/coverages/complex_coverage.py", line 71, in get_parameter_values
    current_time_segment = get_overlap(extents, time_segment)
  File "/Users/luke/Documents/Dev/code/coi2/extern/coverage-model/coverage_model/util/extent_utils.py", line 24, in get_overlap
    raise RuntimeError('No overlap')
RuntimeError: No overlap

----------------------------------------------------------------------
```

**Comment by lukecampbell** [comment]
https://github.com/caseybryant/coverage-model/pull/14

**Comment by lukecampbell** [comment]
I'm gonna ignore retrieve requests time segments of None,None for now but can you look and see if this is really an issue?
